#!/bin/bash

if [ "$GOGUI" == "" ]; then
    export GOGUI="$HOME/prg/go/gogui-1.4.9/bin"
fi

export GOGUI_REGRESS="$GOGUI/gogui-regress"
$GOGUI_REGRESS "./michi gtp" -output tests/output -long tests/fix_atari.tst 
$GOGUI_REGRESS "./michi gtp" -output tests/output -long tests/large_pat.tst 

